### ISSUE TITLE
Compile error when trying to integrate Segment with Optimizely

### ISSUE THREAD

**Issue by DanielTrov** [segment-integrations/analytics-ios-integration-optimizely-x#5]
Hi,

We are trying to integrate Segment with Optimizely and it fails to compile.

I found a possible fix for the issue. Changing in `SEGOptimizelyXIntegration.h` the line `#import "SEGAnalytics.h"` to `#import <Analytics/SEGAnalytics.h>` allows me to compile all the dependencies.

**Comment by ladanazita** [comment]
HI @DanielTrov 

Thanks for catching this - I will update this now.

**Comment by DanielTrov** [comment]
@ladanazita Is it possible to have a new release tag created so I can point to the new one instead of to the commit in the pod file?

**Comment by ladanazita** [comment]
Hey @DanielTrov , 
I'm working on it now; caught something else that needs attention. Will ship together as a new release. Thanks for your patience here.

**Comment by ladanazita** [comment]
Hey @DanielTrov , thanks again for your patience. I released this on 1.0.3-beta. Thanks again for catching this!
