### ISSUE TITLE
Integration does not compile when OptimizelySDKiOS is version 2.0

### ISSUE THREAD

**Issue by kevmalek** [segment-integrations/analytics-ios-integration-optimizely-x#9]
The compiler can't find the variable `OptimizelyDidActivateExperimentNotification` in `SEGOptimizelyXIntegration.m` when the OptimizelySDKiOS library is updated to version 2.0 (https://github.com/optimizely/objective-c-sdk/releases)

**Comment by bsrz** [comment]
temporarily fixed by https://github.com/segment-integrations/analytics-ios-integration-optimizely-x/pull/11

**Comment by kevmalek** [comment]
Hi, is this something that will be addressed? We'd like to move to version 2 of Optimizely's library.

**Comment by brennan** [comment]
Hey @kevmalek, I would recommend implementing Optimizely X in your app using Segment's [cloud mode](https://segment.com/docs/destinations/optimizelyx/#cloud-mode-implementation). For this, you would simply implement the Optimizely X SDK version of your choice and enable the "Optimizely X" component in your Segment dashboard to map Segment `track` events to Optimizely's `track` method. I'd recommend this approach in general - it's a light-weight and straightforward way to send A/B test metrics to Optimizely via Segment.
